# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Web3SwiftExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Web3SwiftExample
	
pod 'web3swift', :git => 'https://github.com/skywinder/web3swift', :branch => 'master'
pod 'Alamofire'
pod 'ReachabilitySwift', '5.0.0'
pod 'TTTAttributedLabel', '2.0.0'
pod 'MBProgressHUD', '~> 1.2.0'
pod 'ESPullToRefresh', '~> 2.9.3'

end
